# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 381bbb09655499a4acc2f5c2f439d1c8166f2b239122247001d77fcce7680076e837d6448329c1ee5a897835702364009eba078e52177eb966b35322f9d1988a

test:
  secret_key_base: 699bdc73e9a5436ceaced77b7286bcc73da0895e24fb2be6ff94f777e313202b2fb4e55c2a75ef5735c9a16369f321de8cb8c56b47805d3416a37d90f3708a72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
